version: 0.5

index_id: rlog

doc_mapping:
  mode: strict
  field_mappings:
    - name: timestamp_secs
      type: datetime
      input_formats: [unix_timestamp]
      indexed: false
      fast: true
      precision: seconds
      stored: false
    - name: timestamp_nanos
      type: u64
      indexed: false
    - name: hostname
      type: text
      tokenizer: raw
    - name: service_name
      type: text
      tokenizer: raw
    - name: severity_text
      type: text
      tokenizer: raw
    - name: severity_number
      type: u64
    - name: body
      type: json
    - name: message
      type: text
      tokenizer: raw

  timestamp_field: timestamp_secs

indexing_settings:
  commit_timeout_secs: 5

search_settings:
  default_search_fields: ["message"]