version: 0.6

index_id: rlog-v0_6

doc_mapping:
  mode: dynamic
  dynamic_mapping:
    indexed: true
    stored: true
    tokenizer: default
    record: position
    expand_dots: true
    fast: true
  field_mappings:
    - name: timestamp
      type: datetime
      input_formats: [unix_timestamp]
      fast: true
      # truncate the fast field to seconds precision
      precision: seconds
      stored: true
    - name: hostname
      type: text
      tokenizer: raw
    - name: service_name
      type: text
      tokenizer: raw
    - name: severity_text
      type: text
      tokenizer: default
    - name: severity_number
      type: u64
    - name: body
      type: json
    - name: message
      type: text
      tokenizer: default
      record: position

  timestamp_field: timestamp

indexing_settings:
  commit_timeout_secs: 5

search_settings:
  default_search_fields: ["message"]

retention:
  period: 12 months
  schedule: daily
