[package]
name = "rlog-shipper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlog-grpc = {path = "../rlog-grpc"}
clap={version = "4", features = ["env", "derive"]}
syslog_loose="0.18"
anyhow="1"
serde={version="1", features=["derive"]}
serde_json="1"
tokio={version="1", features=["macros", "rt-multi-thread"]}
dotenv="0.15"
hostname="0.3"
futures="0.3"