
# OPTIONAL: syslog input configuration
syslog_in:

  # List of exclusion filters to apply to incoming messages
  #
  # If any of defined filters is matching the message will be discarded
  # All filters are defined as Rust Regex on fields "appname", "severity", "message"
  exclusion_filters:
    # message with appname matching the following regex will be excluded
    - appname: "rlog-.*"
    # message of facility "mail" AND appname "postfix" AND matching message regex will be discarded
    - facility: "mail"
      appname: "postfix"
      message: "(disconnect|connect) from"

# OPTIONAL: GELF input configuration
gelf_in:
